# Metal Plate
/gate/module/daughters/name     MetalPlate
/gate/module/daughters/insert   box
/gate/MetalPlate/geometry/setXLength    2. mm
/gate/MetalPlate/geometry/setYLength    107.52 mm
/gate/MetalPlate/geometry/setZLength    20. mm
/gate/MetalPlate/placement/setTranslation  -44 0. 0. mm

# Hole inside the Metal Plate
/gate/MetalPlate/daughters/name hole
/gate/MetalPlate/daughters/insert box
/gate/hole/geometry/setXLength  2. mm
/gate/hole/geometry/setYLength  2. mm
/gate/hole/geometry/setZLength  2. mm
/gate/hole/setMaterial Air
/gate/hole/placement/setTranslation 0. 0 0. mm   # Example translation for the hole

# Hole array placement
/gate/hole/repeaters/insert cubicArray
/gate/hole/cubicArray/setRepeatNumberX 1
/gate/hole/cubicArray/setRepeatNumberY 11
/gate/hole/cubicArray/setRepeatNumberZ 10
/gate/hole/cubicArray/setRepeatVector 0. 10 2. mm

# Metal Plate material and visualization settings
/gate/MetalPlate/setMaterial Tungsten
/gate/MetalPlate/vis/setColor blue
/gate/MetalPlate/vis/forceWireframe
#/gate/MetalPlate/vis/forceSolid   # Uncomment if you want it solid
/gate/MetalPlate/vis/setVisible 1

