#=====================================================
# D I G I T I Z E R
#=====================================================
/gate/digitizerMgr/xlayer0/SinglesDigitizer/Singles/insert                        adder
/gate/digitizerMgr/xlayer1/SinglesDigitizer/Singles/insert                        adder
/gate/digitizerMgr/xlayer2/SinglesDigitizer/Singles/insert                        adder
/gate/digitizerMgr/xlayer3/SinglesDigitizer/Singles/insert                        adder

# xlayer0
/gate/digitizerMgr/xlayer0/SinglesDigitizer/Singles/insert energyResolution
/gate/digitizerMgr/xlayer0/SinglesDigitizer/Singles/energyResolution/fwhm 0.10
/gate/digitizerMgr/xlayer0/SinglesDigitizer/Singles/energyResolution/energyOfReference 140. keV
/gate/digitizerMgr/xlayer0/SinglesDigitizer/Singles/insert spatialResolution

/gate/digitizerMgr/xlayer0/SinglesDigitizer/Singles/spatialResolution/fwhm 1.0 mm
/gate/digitizerMgr/xlayer0/SinglesDigitizer/Singles/spatialResolution/confineInsideOfSmallestElement true
/gate/digitizerMgr/xlayer0/SinglesDigitizer/Singles/spatialResolution/verbose 0
/gate/digitizerMgr/xlayer0/SinglesDigitizer/Singles/insert energyFraming
/gate/digitizerMgr/xlayer0/SinglesDigitizer/Singles/energyFraming/setMin 20. keV
/gate/digitizerMgr/xlayer0/SinglesDigitizer/Singles/energyFraming/setMax 190. keV

# xlayer1
/gate/digitizerMgr/xlayer1/SinglesDigitizer/Singles/insert energyResolution
/gate/digitizerMgr/xlayer1/SinglesDigitizer/Singles/energyResolution/fwhm 0.10
/gate/digitizerMgr/xlayer1/SinglesDigitizer/Singles/energyResolution/energyOfReference 140. keV
/gate/digitizerMgr/xlayer1/SinglesDigitizer/Singles/insert spatialResolution

/gate/digitizerMgr/xlayer1/SinglesDigitizer/Singles/spatialResolution/fwhm 1.0 mm
/gate/digitizerMgr/xlayer1/SinglesDigitizer/Singles/spatialResolution/confineInsideOfSmallestElement true
/gate/digitizerMgr/xlayer1/SinglesDigitizer/Singles/spatialResolution/verbose 0
/gate/digitizerMgr/xlayer1/SinglesDigitizer/Singles/insert energyFraming
/gate/digitizerMgr/xlayer1/SinglesDigitizer/Singles/energyFraming/setMin 20. keV
/gate/digitizerMgr/xlayer1/SinglesDigitizer/Singles/energyFraming/setMax 190. keV

# xlayer2
/gate/digitizerMgr/xlayer2/SinglesDigitizer/Singles/insert energyResolution
/gate/digitizerMgr/xlayer2/SinglesDigitizer/Singles/energyResolution/fwhm 0.10
/gate/digitizerMgr/xlayer2/SinglesDigitizer/Singles/energyResolution/energyOfReference 140. keV
/gate/digitizerMgr/xlayer2/SinglesDigitizer/Singles/insert spatialResolution

/gate/digitizerMgr/xlayer2/SinglesDigitizer/Singles/spatialResolution/fwhm 1.0 mm
/gate/digitizerMgr/xlayer2/SinglesDigitizer/Singles/spatialResolution/confineInsideOfSmallestElement true
/gate/digitizerMgr/xlayer2/SinglesDigitizer/Singles/spatialResolution/verbose 0
/gate/digitizerMgr/xlayer2/SinglesDigitizer/Singles/insert energyFraming
/gate/digitizerMgr/xlayer2/SinglesDigitizer/Singles/energyFraming/setMin 20. keV
/gate/digitizerMgr/xlayer2/SinglesDigitizer/Singles/energyFraming/setMax 190. keV

# xlayer3
/gate/digitizerMgr/xlayer3/SinglesDigitizer/Singles/insert energyResolution
/gate/digitizerMgr/xlayer3/SinglesDigitizer/Singles/energyResolution/fwhm 0.10
/gate/digitizerMgr/xlayer3/SinglesDigitizer/Singles/energyResolution/energyOfReference 140. keV
/gate/digitizerMgr/xlayer3/SinglesDigitizer/Singles/insert spatialResolution

/gate/digitizerMgr/xlayer3/SinglesDigitizer/Singles/spatialResolution/fwhm 1.0 mm
/gate/digitizerMgr/xlayer3/SinglesDigitizer/Singles/spatialResolution/confineInsideOfSmallestElement true
/gate/digitizerMgr/xlayer3/SinglesDigitizer/Singles/spatialResolution/verbose 0
/gate/digitizerMgr/xlayer3/SinglesDigitizer/Singles/insert energyFraming
/gate/digitizerMgr/xlayer3/SinglesDigitizer/Singles/energyFraming/setMin 20. keV
/gate/digitizerMgr/xlayer3/SinglesDigitizer/Singles/energyFraming/setMax 190. keV