/gate/digitizerMgr/xlayer1/SinglesDigitizer/Singles/insert                        adder 


/gate/digitizerMgr/xlayer1/SinglesDigitizer/Singles/insert energyResolution 
/gate/digitizerMgr/xlayer1/SinglesDigitizer/Singles/energyResolution/fwhm 0.10 
/gate/digitizerMgr/xlayer1/SinglesDigitizer/Singles/energyResolution/energyOfReference 140. keV 
/gate/digitizerMgr/xlayer1/SinglesDigitizer/Singles/insert spatialResolution 

/gate/digitizerMgr/xlayer1/SinglesDigitizer/Singles/spatialResolution/fwhm 1.0 mm 
/gate/digitizerMgr/xlayer1/SinglesDigitizer/Singles/spatialResolution/confineInsideOfSmallestElement true 
/gate/digitizerMgr/xlayer1/SinglesDigitizer/Singles/spatialResolution/verbose 0 
/gate/digitizerMgr/xlayer1/SinglesDigitizer/Singles/insert energyFraming 
/gate/digitizerMgr/xlayer1/SinglesDigitizer/Singles/energyFraming/setMin 120. keV 
/gate/digitizerMgr/xlayer1/SinglesDigitizer/Singles/energyFraming/setMax 160. keV 


