
/gate/cylindricalPET/daughters/name     CollimatorPlate
/gate/cylindricalPET/daughters/insert   cylinder
/gate/CollimatorPlate/geometry/setRmin  210. mm
/gate/CollimatorPlate/geometry/setRmax  220. mm
/gate/CollimatorPlate/geometry/setHeight 20. mm
/gate/CollimatorPlate/placement/setTranslation 0. 0. 100. mm   
/gate/CollimatorPlate/setMaterial       Tungsten
/gate/CollimatorPlate/vis/setColor      blue
/gate/CollimatorPlate/vis/forceWireframe
/gate/CollimatorPlate/vis/setVisible    1

/gate/cylindricalPET/daughters/name     CollimatorModule
/gate/cylindricalPET/daughters/insert   box
/gate/CollimatorModule/geometry/setXLength  1. mm
/gate/CollimatorModule/geometry/setYLength  1. mm
/gate/CollimatorModule/geometry/setZLength  1. mm
/gate/CollimatorModule/placement/setTranslation 215. 0. 100. mm  
/gate/CollimatorModule/setMaterial      Air
/gate/CollimatorModule/vis/setVisible   0




/gate/CollimatorModule/daughters/name   pinhole
/gate/CollimatorModule/daughters/insert cone
/gate/pinhole/geometry/setRmin1         0. mm
/gate/pinhole/geometry/setRmax1         1.5 mm      
/gate/pinhole/geometry/setRmin2         0. mm
/gate/pinhole/geometry/setRmax2         2.5 mm
/gate/pinhole/geometry/setHeight        20. mm
/gate/pinhole/placement/setTranslation  0. 0. 0. mm
/gate/pinhole/setMaterial               Air
/gate/pinhole/vis/setColor              white
/gate/pinhole/vis/forceWireframe
/gate/pinhole/vis/setVisible            1



/gate/CollimatorModule/repeaters/insert ring
/gate/CollimatorModule/ring/setRepeatNumber       18
/gate/CollimatorModule/ring/setFirstAngle         0. deg
/gate/CollimatorModule/ring/setAngularSpan        360. deg



/gate/pinhole/placement/setRotationAxis 0 1 0
/gate/pinhole/placement/setRotationAngle 90.0 deg


