# M A N D A T O R Y
/gate/geometry/setMaterialDatabase GateMaterials.db

#/control/execute geometry.mac


/control/execute MPHtestgeometry.mac
#/control/execute plate.mac

#/control/execute correctgeom.mac
#/control/execute temp.mac
/control/execute MPHplate.mac



#/control/execute rotplate.mac
/control/execute MPHsystem.mac
/control/execute MPHphysics.mac

/gate/run/initialize
#/control/execute visual.mac

/control/execute MPHdigitizer.mac
/control/execute MPHsource.mac
#/control/execute DeRenzoProper.mac

/gate/random/setEngineName MersenneTwister
#/gate/random/setSeeds 0 
/gate/random/setEngineSeed 0 

# Experiment
#/gate/application/setTimeSlice      0.005  s
/gate/application/setTimeStart      0. s
/gate/application/setTimeStop      1 s

# V E R B O S I T Y
/control/execute verbose.mac

# Output
/control/execute MPHoutput.mac

# L E T' S   R U N   T H E   S I M U L A T I O N  !
/gate/application/startDAQ

