############################# IZ 90mm #############################
/gate/source/addSource source1
/gate/source/source1/gps/particle gamma

/gate/source/source1/gps/energytype   Mono
/gate/source/source1/gps/monoenergy   140.0 keV
/gate/source/source1/setActivity      0.0001 Ci        #0.005Ci 40min

# IZ1
/gate/source/source1/gps/centre  0. 0. 0. mm
/gate/source/source1/gps/type    Plane
/gate/source/source1/gps/shape   Rectangle
/gate/source/source1/gps/halfx   400 mm   
/gate/source/source1/gps/halfy   400 mm   
/gate/source/source1/gps/angtype iso


#/gate/source/source1/gps/centre 0. 0. 0. mm
#/gate/source/source1/gps/type    Volume
#/gate/source/source1/gps/shape   Cylinder
#/gate/source/source1/gps/angtype iso
#/gate/source/source1/gps/radius  100. mm
#/gate/source/source1/gps/halfz   2570 mm
#/gate/source/source1/gps/direction 1 0 0


/gate/source/source1/gps/mintheta 90 deg   # Full isotropic emission
/gate/source/source1/gps/maxtheta 90 deg
/gate/source/source1/gps/minphi   0 deg
/gate/source/source1/gps/maxphi   360 deg

/gate/source/list
