/gate/world/geometry/setXLength 1800 mm
/gate/world/geometry/setYLength 1800 mm
/gate/world/geometry/setZLength 1800 mm

/gate/world/daughters/name cylindricalPET
/gate/world/daughters/insert cylinder
/gate/cylindricalPET/placement/setTranslation 0.0 0.0 0.0 mm
/gate/cylindricalPET/geometry/setRmax 900.0 mm
/gate/cylindricalPET/geometry/setRmin 0 mm
/gate/cylindricalPET/geometry/setHeight 200 mm
/gate/cylindricalPET/setMaterial Air
/gate/cylindricalPET/vis/forceWireframe
/gate/cylindricalPET/vis/setColor white
/gate/cylindricalPET/vis/setVisible 0

/gate/cylindricalPET/daughters/name panel
/gate/cylindricalPET/daughters/insert box
/gate/panel/geometry/setXLength 100 mm    # Sized for module
/gate/panel/geometry/setYLength 108 mm
/gate/panel/geometry/setZLength 20 mm    # Sized for stack
/gate/panel/placement/setTranslation 757 0. 0. mm
/gate/panel/setMaterial Air
/gate/panel/vis/setVisible 0

/gate/panel/daughters/name module
/gate/panel/daughters/insert box
/gate/module/geometry/setXLength 97 mm   # Fits block size
/gate/module/geometry/setYLength 108 mm
/gate/module/geometry/setZLength 20 mm
/gate/module/vis/setColor white
/gate/module/vis/setVisible 0
/gate/module/setMaterial Air

/gate/module/daughters/name block
/gate/module/daughters/insert box
/gate/block/geometry/setXLength 27 mm
/gate/block/geometry/setYLength 108 mm
/gate/block/geometry/setZLength 20 mm   # Fits zlayer repetitions
/gate/block/vis/setColor white
/gate/block/vis/setVisible 0
/gate/block/setMaterial Air

/gate/block/daughters/name zlayer
/gate/block/daughters/insert box
/gate/zlayer/geometry/setXLength 27 mm   # Accommodates all xlayers
/gate/zlayer/geometry/setYLength 108 mm
/gate/zlayer/geometry/setZLength 3 mm    # Single zlayer height
/gate/zlayer/vis/setColor white
/gate/zlayer/vis/setVisible 0
/gate/zlayer/setMaterial Air

/gate/zlayer/daughters/name xlayer1 
/gate/zlayer/daughters/insert box
/gate/xlayer1/geometry/setXLength 3 mm    # Detector size
/gate/xlayer1/geometry/setYLength 3 mm    # Detector size
/gate/xlayer1/geometry/setZLength 3 mm    # Detector size
/gate/xlayer1/vis/setColor yellow
/gate/xlayer1/vis/forceSolid
/gate/xlayer1/setMaterial GAGG







/gate/panel/repeaters/insert ring
/gate/module/repeaters/insert linear
/gate/block/repeaters/insert linear
/gate/zlayer/repeaters/insert linear

/gate/xlayer1/repeaters/insert linear


/gate/panel/ring/setRepeatNumber 1360
/gate/module/linear/setRepeatNumber 1
/gate/block/linear/setRepeatNumber 1
/gate/zlayer/linear/setRepeatNumber 1

/gate/xlayer1/linear/setRepeatNumber 1
/gate/xlayer1/linear/setRepeatVector 0.  6.72  0. mm


