#=====================================================
# D I G I T I Z E R
#=====================================================
/gate/digitizerMgr/xlayer1/SinglesDigitizer/Singles/insert                        adder 

# xlayer1 
/gate/digitizerMgr/xlayer1/SinglesDigitizer/Singles/insert energyResolution 
/gate/digitizerMgr/xlayer1/SinglesDigitizer/Singles/energyResolution/fwhm 0.10 
/gate/digitizerMgr/xlayer1/SinglesDigitizer/Singles/energyResolution/energyOfReference 140. keV 
/gate/digitizerMgr/xlayer1/SinglesDigitizer/Singles/insert spatialResolution 

/gate/digitizerMgr/xlayer1/SinglesDigitizer/Singles/spatialResolution/fwhm 1.0 mm 
/gate/digitizerMgr/xlayer1/SinglesDigitizer/Singles/spatialResolution/confineInsideOfSmallestElement true 
/gate/digitizerMgr/xlayer1/SinglesDigitizer/Singles/spatialResolution/verbose 0 
/gate/digitizerMgr/xlayer1/SinglesDigitizer/Singles/insert energyFraming 
/gate/digitizerMgr/xlayer1/SinglesDigitizer/Singles/energyFraming/setMin 20. keV 
/gate/digitizerMgr/xlayer1/SinglesDigitizer/Singles/energyFraming/setMax 190. keV 

/gate/digitizerMgr/xlayer2/SinglesDigitizer/Singles/insert adder

# xlayer2
/gate/digitizerMgr/xlayer2/SinglesDigitizer/Singles/insert energyResolution 
/gate/digitizerMgr/xlayer2/SinglesDigitizer/Singles/energyResolution/fwhm 0.10 
/gate/digitizerMgr/xlayer2/SinglesDigitizer/Singles/energyResolution/energyOfReference 140. keV 
/gate/digitizerMgr/xlayer2/SinglesDigitizer/Singles/insert spatialResolution 

/gate/digitizerMgr/xlayer2/SinglesDigitizer/Singles/spatialResolution/fwhm 1.0 mm 
/gate/digitizerMgr/xlayer2/SinglesDigitizer/Singles/spatialResolution/confineInsideOfSmallestElement true 
/gate/digitizerMgr/xlayer2/SinglesDigitizer/Singles/spatialResolution/verbose 0 
/gate/digitizerMgr/xlayer2/SinglesDigitizer/Singles/insert energyFraming 
/gate/digitizerMgr/xlayer2/SinglesDigitizer/Singles/energyFraming/setMin 20. keV 
/gate/digitizerMgr/xlayer2/SinglesDigitizer/Singles/energyFraming/setMax 190. keV 

/gate/digitizerMgr/xlayer3/SinglesDigitizer/Singles/insert adder

# xlayer3
/gate/digitizerMgr/xlayer3/SinglesDigitizer/Singles/insert energyResolution 
/gate/digitizerMgr/xlayer3/SinglesDigitizer/Singles/energyResolution/fwhm 0.10 
/gate/digitizerMgr/xlayer3/SinglesDigitizer/Singles/energyResolution/energyOfReference 140. keV 
/gate/digitizerMgr/xlayer3/SinglesDigitizer/Singles/insert spatialResolution 

/gate/digitizerMgr/xlayer3/SinglesDigitizer/Singles/spatialResolution/fwhm 1.0 mm 
/gate/digitizerMgr/xlayer3/SinglesDigitizer/Singles/spatialResolution/confineInsideOfSmallestElement true 
/gate/digitizerMgr/xlayer3/SinglesDigitizer/Singles/spatialResolution/verbose 0 
/gate/digitizerMgr/xlayer3/SinglesDigitizer/Singles/insert energyFraming 
/gate/digitizerMgr/xlayer3/SinglesDigitizer/Singles/energyFraming/setMin 20. keV 
/gate/digitizerMgr/xlayer3/SinglesDigitizer/Singles/energyFraming/setMax 190. keV 

/gate/digitizerMgr/xlayer4/SinglesDigitizer/Singles/insert adder

# xlayer4
/gate/digitizerMgr/xlayer4/SinglesDigitizer/Singles/insert energyResolution 
/gate/digitizerMgr/xlayer4/SinglesDigitizer/Singles/energyResolution/fwhm 0.10 
/gate/digitizerMgr/xlayer4/SinglesDigitizer/Singles/energyResolution/energyOfReference 140. keV 
/gate/digitizerMgr/xlayer4/SinglesDigitizer/Singles/insert spatialResolution 

/gate/digitizerMgr/xlayer4/SinglesDigitizer/Singles/spatialResolution/fwhm 1.0 mm 
/gate/digitizerMgr/xlayer4/SinglesDigitizer/Singles/spatialResolution/confineInsideOfSmallestElement true 
/gate/digitizerMgr/xlayer4/SinglesDigitizer/Singles/spatialResolution/verbose 0 
/gate/digitizerMgr/xlayer4/SinglesDigitizer/Singles/insert energyFraming 
/gate/digitizerMgr/xlayer4/SinglesDigitizer/Singles/energyFraming/setMin 20. keV 
/gate/digitizerMgr/xlayer4/SinglesDigitizer/Singles/energyFraming/setMax 190. keV 

/gate/digitizerMgr/xlayer5/SinglesDigitizer/Singles/insert adder

# xlayer5
/gate/digitizerMgr/xlayer5/SinglesDigitizer/Singles/insert energyResolution 
/gate/digitizerMgr/xlayer5/SinglesDigitizer/Singles/energyResolution/fwhm 0.10 
/gate/digitizerMgr/xlayer5/SinglesDigitizer/Singles/energyResolution/energyOfReference 140. keV 
/gate/digitizerMgr/xlayer5/SinglesDigitizer/Singles/insert spatialResolution 

/gate/digitizerMgr/xlayer5/SinglesDigitizer/Singles/spatialResolution/fwhm 1.0 mm 
/gate/digitizerMgr/xlayer5/SinglesDigitizer/Singles/spatialResolution/confineInsideOfSmallestElement true 
/gate/digitizerMgr/xlayer5/SinglesDigitizer/Singles/spatialResolution/verbose 0 
/gate/digitizerMgr/xlayer5/SinglesDigitizer/Singles/insert energyFraming 
/gate/digitizerMgr/xlayer5/SinglesDigitizer/Singles/energyFraming/setMin 20. keV 
/gate/digitizerMgr/xlayer5/SinglesDigitizer/Singles/energyFraming/setMax 190. keV 

/gate/digitizerMgr/xlayer6/SinglesDigitizer/Singles/insert adder

# xlayer6
/gate/digitizerMgr/xlayer6/SinglesDigitizer/Singles/insert energyResolution 
/gate/digitizerMgr/xlayer6/SinglesDigitizer/Singles/energyResolution/fwhm 0.10 
/gate/digitizerMgr/xlayer6/SinglesDigitizer/Singles/energyResolution/energyOfReference 140. keV 
/gate/digitizerMgr/xlayer6/SinglesDigitizer/Singles/insert spatialResolution 

/gate/digitizerMgr/xlayer6/SinglesDigitizer/Singles/spatialResolution/fwhm 1.0 mm 
/gate/digitizerMgr/xlayer6/SinglesDigitizer/Singles/spatialResolution/confineInsideOfSmallestElement true 
/gate/digitizerMgr/xlayer6/SinglesDigitizer/Singles/spatialResolution/verbose 0 
/gate/digitizerMgr/xlayer6/SinglesDigitizer/Singles/insert energyFraming 
/gate/digitizerMgr/xlayer6/SinglesDigitizer/Singles/energyFraming/setMin 20. keV 
/gate/digitizerMgr/xlayer6/SinglesDigitizer/Singles/energyFraming/setMax 190. keV 

/gate/digitizerMgr/xlayer7/SinglesDigitizer/Singles/insert adder

# xlayer7
/gate/digitizerMgr/xlayer7/SinglesDigitizer/Singles/insert energyResolution 
/gate/digitizerMgr/xlayer7/SinglesDigitizer/Singles/energyResolution/fwhm 0.10 
/gate/digitizerMgr/xlayer7/SinglesDigitizer/Singles/energyResolution/energyOfReference 140. keV 
/gate/digitizerMgr/xlayer7/SinglesDigitizer/Singles/insert spatialResolution 

/gate/digitizerMgr/xlayer7/SinglesDigitizer/Singles/spatialResolution/fwhm 1.0 mm 
/gate/digitizerMgr/xlayer7/SinglesDigitizer/Singles/spatialResolution/confineInsideOfSmallestElement true 
/gate/digitizerMgr/xlayer7/SinglesDigitizer/Singles/spatialResolution/verbose 0 
/gate/digitizerMgr/xlayer7/SinglesDigitizer/Singles/insert energyFraming 
/gate/digitizerMgr/xlayer7/SinglesDigitizer/Singles/energyFraming/setMin 20. keV 
/gate/digitizerMgr/xlayer7/SinglesDigitizer/Singles/energyFraming/setMax 190. keV 

/gate/digitizerMgr/xlayer8/SinglesDigitizer/Singles/insert adder

# xlayer8
/gate/digitizerMgr/xlayer8/SinglesDigitizer/Singles/insert energyResolution 
/gate/digitizerMgr/xlayer8/SinglesDigitizer/Singles/energyResolution/fwhm 0.10 
/gate/digitizerMgr/xlayer8/SinglesDigitizer/Singles/energyResolution/energyOfReference 140. keV 
/gate/digitizerMgr/xlayer8/SinglesDigitizer/Singles/insert spatialResolution 

/gate/digitizerMgr/xlayer8/SinglesDigitizer/Singles/spatialResolution/fwhm 1.0 mm 
/gate/digitizerMgr/xlayer8/SinglesDigitizer/Singles/spatialResolution/confineInsideOfSmallestElement true 
/gate/digitizerMgr/xlayer8/SinglesDigitizer/Singles/spatialResolution/verbose 0 
/gate/digitizerMgr/xlayer8/SinglesDigitizer/Singles/insert energyFraming 
/gate/digitizerMgr/xlayer8/SinglesDigitizer/Singles/energyFraming/setMin 20. keV 
/gate/digitizerMgr/xlayer8/SinglesDigitizer/Singles/energyFraming/setMax 190. keV 

