# G E O M E T R Y
#####

# World
# Define the world dimensions
##
/gate/world/geometry/setXLength 300 mm
/gate/world/geometry/setYLength 300 mm
/gate/world/geometry/setZLength 300 mm

/gate/world/daughters/name                    cylindricalPET
/gate/world/daughters/insert                  cylinder
/gate/cylindricalPET/placement/setTranslation 0.0 0.0 0.0 mm
/gate/cylindricalPET/geometry/setRmax        150.0 mm
/gate/cylindricalPET/geometry/setRmin         100 mm
/gate/cylindricalPET/geometry/setHeight       20 cm
/gate/cylindricalPET/setMaterial              Air
/gate/cylindricalPET/vis/forceWireframe
/gate/cylindricalPET/vis/setColor             white
/gate/cylindricalPET/vis/setVisible 0

/gate/cylindricalPET/daughters/name panel
/gate/cylindricalPET/daughters/insert box
/gate/panel/geometry/setXLength 30 mm
/gate/panel/geometry/setYLength 108 mm
/gate/panel/geometry/setZLength 10. mm
/gate/panel/placement/setTranslation 111.76 0. 0. mm
#/gate/panel/placement/setTranslation 0 0. 0. mm
/gate/panel/setMaterial Air

#/gate/panel/ring/setRepeatNumber 1
/gate/panel/vis/setVisible 0

/gate/panel/daughters/name     module
/gate/panel/daughters/insert   box
/gate/module/geometry/setXLength           27 mm
/gate/module/geometry/setYLength           108  mm
/gate/module/geometry/setZLength           20. mm
/gate/module/vis/setColor white
#/gate/module/vis/forceSolid

/gate/module/vis/setVisible 0
/gate/module/setMaterial Air




/gate/module/daughters/name     block
/gate/module/daughters/insert   box
/gate/block/geometry/setXLength           26.88 mm
/gate/block/geometry/setYLength           26.88 mm
/gate/block/geometry/setZLength           20. mm
/gate/block/vis/setColor white

/gate/block/vis/setVisible 0
/gate/block/setMaterial Air

/gate/block/daughters/name     zlayer4x4
/gate/block/daughters/insert   box
/gate/zlayer4x4/geometry/setXLength           13.44 mm
/gate/zlayer4x4/geometry/setYLength           13.44 mm
/gate/zlayer4x4/geometry/setZLength           4. mm


/gate/zlayer4x4/vis/setColor white
/gate/zlayer4x4/vis/forceSolid
/gate/zlayer4x4/setMaterial Air
/gate/zlayer4x4/vis/setVisible 0

/gate/zlayer4x4/daughters/name xlayer0
/gate/zlayer4x4/daughters/insert   box
/gate/xlayer0/geometry/setXLength           3. mm
/gate/xlayer0/geometry/setYLength           2. mm
/gate/xlayer0/geometry/setZLength           4. mm
/gate/xlayer0/placement/setTranslation  -5.04 -1.68 0. mm


/gate/zlayer4x4/daughters/name xlayer1
/gate/zlayer4x4/daughters/insert   box
/gate/xlayer1/geometry/setXLength           3. mm
/gate/xlayer1/geometry/setYLength           2. mm
/gate/xlayer1/geometry/setZLength           4. mm
/gate/xlayer1/placement/setTranslation  -1.68 1.68 0. mm

/gate/zlayer4x4/daughters/name xlayer2
/gate/zlayer4x4/daughters/insert   box
/gate/xlayer2/geometry/setXLength           3. mm
/gate/xlayer2/geometry/setYLength           2. mm
/gate/xlayer2/geometry/setZLength           4. mm
/gate/xlayer2/placement/setTranslation  1.68 -1.68 0. mm

/gate/zlayer4x4/daughters/name xlayer3
/gate/zlayer4x4/daughters/insert   box
/gate/xlayer3/geometry/setXLength           3. mm
/gate/xlayer3/geometry/setYLength           2. mm
/gate/xlayer3/geometry/setZLength           4. mm
/gate/xlayer3/placement/setTranslation  5.04 1.68 0. mm

/gate/xlayer0/vis/setColor yellow
/gate/xlayer1/vis/setColor yellow
/gate/xlayer2/vis/setColor yellow
/gate/xlayer3/vis/setColor yellow
/gate/xlayer0/vis/forceSolid
/gate/xlayer1/vis/forceSolid
/gate/xlayer2/vis/forceSolid
/gate/xlayer3/vis/forceSolid

/gate/xlayer0/setMaterial GAGG
/gate/xlayer1/setMaterial GAGG
/gate/xlayer2/setMaterial GAGG
/gate/xlayer3/setMaterial GAGG

#/gate/xlayer0/setMaterial Air
#/gate/xlayer1/setMaterial Air
#/gate/xlayer2/setMaterial Air
#/gate/xlayer3/setMaterial Air


/gate/panel/repeaters/insert ring
/gate/module/repeaters/insert linear
/gate/block/repeaters/insert linear
/gate/zlayer4x4/repeaters/insert cubicArray
/gate/xlayer0/repeaters/insert linear
/gate/xlayer1/repeaters/insert linear
/gate/xlayer2/repeaters/insert linear
/gate/xlayer3/repeaters/insert linear


/gate/panel/ring/setRepeatNumber 6
/gate/module/linear/setRepeatNumber 1
/gate/block/linear/setRepeatNumber 4
/gate/zlayer4x4/cubicArray/setRepeatNumberX  2
/gate/zlayer4x4/cubicArray/setRepeatNumberY  2
/gate/zlayer4x4/cubicArray/setRepeatNumberZ  1
/gate/xlayer0/linear/setRepeatNumber 2
/gate/xlayer1/linear/setRepeatNumber 2
/gate/xlayer2/linear/setRepeatNumber 2
/gate/xlayer3/linear/setRepeatNumber 2

/gate/module/linear/setRepeatVector 0. 0. 20. mm
/gate/block/linear/setRepeatVector 0. 26.88 0. mm
/gate/zlayer4x4/cubicArray/setRepeatVector   13.44 13.44 4. mm
/gate/xlayer0/linear/setRepeatVector 0. 6.72 0. mm
/gate/xlayer1/linear/setRepeatVector 0. 6.72 0. mm
/gate/xlayer2/linear/setRepeatVector 0. 6.72 0. mm
/gate/xlayer3/linear/setRepeatVector 0. 6.72 0. mm