# Metal Plate
/gate/module/daughters/name     MetalPlate
/gate/module/daughters/insert   box
/gate/MetalPlate/geometry/setXLength    2. mm
/gate/MetalPlate/geometry/setYLength    107.52 mm
/gate/MetalPlate/geometry/setZLength    20. mm
/gate/MetalPlate/placement/setTranslation  -14.44 0. 0. mm

/gate/MetalPlate/daughters/name hole
/gate/MetalPlate/daughters/insert box
/gate/hole/geometry/setXLength  2. mm
/gate/hole/geometry/setYLength  4. mm
/gate/hole/geometry/setZLength  2. mm
/gate/hole/setMaterial Air
#/gate/hole/vis/forceSolid
/gate/hole/vis/forceWireframe
#
# Repeat the hole in an array
##
/gate/hole/repeaters/insert cubicArray
/gate/hole/cubicArray/setRepeatNumberX 1
/gate/hole/cubicArray/setRepeatNumberY 21
/gate/hole/cubicArray/setRepeatNumberZ 5
/gate/hole/cubicArray/setRepeatVector 0. 5.  4. mm

/gate/MetalPlate/setMaterial Tungsten
/gate/MetalPlate/vis/setColor blue
#/gate/MetalPlate/vis/forceSolid
/gate/MetalPlate/vis/forceWireframe
/gate/MetalPlate/vis/setVisible 1