#=====================================================
# PHYSICS
#=====================================================

/gate/physics/addProcess PhotoElectric
/gate/physics/processes/PhotoElectric/setModel StandardModel

#/gate/physics/addProcess Compton
#/gate/physics/processes/Compton/setModel StandardModel

#/gate/physics/addProcess RayleighScattering
#/gate/physics/processes/RayleighScattering/setModel PenelopeModel

#/gate/physics/addProcess ElectronIonisation
#/gate/physics/processes/ElectronIonisation/setModel StandardModel e-
#/gate/physics/processes/ElectronIonisation/setModel StandardModel e+

#/gate/physics/addProcess Bremsstrahlung
#/gate/physics/processes/Bremsstrahlung/setModel StandardModel e-
#/gate/physics/processes/Bremsstrahlung/setModel StandardModel e+

#/gate/physics/addProcess PositronAnnihilation

#/gate/physics/addProcess MultipleScattering e+
#/gate/physics/addProcess MultipleScattering e-

/gate/physics/processList Enabled
/gate/physics/processList Initialized

#=====================================================
# CUTS
#=====================================================

/gate/physics/Gamma/SetCutInRegion      xlayer0 1.0 cm
/gate/physics/Electron/SetCutInRegion   xlayer0 1.0 cm
/gate/physics/Positron/SetCutInRegion   xlayer0 1.0 cm

/gate/physics/Gamma/SetCutInRegion      xlayer1 1.0 cm
/gate/physics/Electron/SetCutInRegion   xlayer1 1.0 cm
/gate/physics/Positron/SetCutInRegion   xlayer1 1.0 cm

/gate/physics/Gamma/SetCutInRegion      xlayer2 1.0 cm
/gate/physics/Electron/SetCutInRegion   xlayer2 1.0 cm
/gate/physics/Positron/SetCutInRegion   xlayer2 1.0 cm

/gate/physics/Gamma/SetCutInRegion      xlayer3 1.0 cm
/gate/physics/Electron/SetCutInRegion   xlayer3 1.0 cm
/gate/physics/Positron/SetCutInRegion   xlayer3 1.0 cm



#/gate/physics/Gamma/SetCutInRegion      phantom 0.1 mm
#/gate/physics/Electron/SetCutInRegion   phantom 0.1 mm
#/gate/physics/Positron/SetCutInRegion   phantom 0.1 mm

#/gate/physics/SetMaxStepSizeInRegion    phantom 0.01 mm