# source Tc99m 

############################# IZ 90mm #############################
/gate/source/addSource source1
/gate/source/source1/gps/particle gamma

/gate/source/source1/gps/energytype   Mono 
/gate/source/source1/gps/monoenergy   140.0 keV
/gate/source/source1/setActivity      0.0001 Ci        #0.005Ci 40min



#IZ1
/gate/source/source1/gps/centre 0. 0. 0. mm
/gate/source/source1/gps/type    Volume
/gate/source/source1/gps/shape   Cylinder
/gate/source/source1/gps/angtype iso
/gate/source/source1/gps/radius  90. mm
/gate/source/source1/gps/halfz   0.5 mm
 
#/gate/source/source1/gps/maxtheta 30 deg   
#/gate/source/source1/gps/mintheta 150 deg
/gate/source/source1/gps/mintheta 90 deg
/gate/source/source1/gps/maxtheta 90 deg
/gate/source/source1/gps/minphi   -2 deg
/gate/source/source1/gps/maxphi    2 deg


/gate/source/list

