#	A T T A C H    S Y S T E M 
/gate/systems/cylindricalPET/rsector/attach     panel
/gate/systems/cylindricalPET/module/attach      module
/gate/systems/cylindricalPET/submodule/attach   block
/gate/systems/cylindricalPET/crystal/attach   zlayer4x4
/gate/systems/cylindricalPET/layer0/attach    xlayer0
/gate/systems/cylindricalPET/layer1/attach    xlayer1
/gate/systems/cylindricalPET/layer2/attach    xlayer2
/gate/systems/cylindricalPET/layer3/attach    xlayer3



#	A T T A C H    C R Y S T A L  SD

/gate/xlayer0/attachCrystalSD
/gate/xlayer1/attachCrystalSD
/gate/xlayer2/attachCrystalSD
/gate/xlayer3/attachCrystalSD

/gate/systems/cylindricalPET/describe