# G E O M E T R Y
#####

# World
/gate/world/geometry/setXLength 1000 mm
/gate/world/geometry/setYLength 1000 mm
/gate/world/geometry/setZLength 1000 mm

/gate/world/daughters/name cylindricalPET
/gate/world/daughters/insert cylinder
/gate/cylindricalPET/placement/setTranslation 0.0 0.0 0.0 mm
/gate/cylindricalPET/geometry/setRmax 1500.0 mm
/gate/cylindricalPET/geometry/setRmin 100 mm
/gate/cylindricalPET/geometry/setHeight 200 mm
/gate/cylindricalPET/setMaterial Air
/gate/cylindricalPET/vis/forceWireframe
/gate/cylindricalPET/vis/setColor white
/gate/cylindricalPET/vis/setVisible 0

/gate/cylindricalPET/daughters/name panel
/gate/cylindricalPET/daughters/insert box
/gate/panel/geometry/setXLength 100 mm    # Sized for module
/gate/panel/geometry/setYLength 108 mm
/gate/panel/geometry/setZLength 20 mm    # Sized for stack
/gate/panel/placement/setTranslation 914 0. 0. mm
/gate/panel/setMaterial Air
/gate/panel/vis/setVisible 0

/gate/panel/daughters/name module
/gate/panel/daughters/insert box
/gate/module/geometry/setXLength 197 mm   # Fits block size
/gate/module/geometry/setYLength 108 mm
/gate/module/geometry/setZLength 20 mm
/gate/module/vis/setColor white
/gate/module/vis/setVisible 0
/gate/module/setMaterial Air

/gate/module/daughters/name block
/gate/module/daughters/insert box
/gate/block/geometry/setXLength 27 mm
/gate/block/geometry/setYLength 108 mm
/gate/block/geometry/setZLength 20 mm   # Fits zlayer repetitions
/gate/block/vis/setColor white
/gate/block/vis/setVisible 0
/gate/block/setMaterial Air

/gate/block/daughters/name zlayer
/gate/block/daughters/insert box
/gate/zlayer/geometry/setXLength 27 mm   # Accommodates all xlayers
/gate/zlayer/geometry/setYLength 108 mm
/gate/zlayer/geometry/setZLength 3 mm    # Single zlayer height
/gate/zlayer/vis/setColor white
/gate/zlayer/vis/setVisible 0
/gate/zlayer/setMaterial Air

/gate/zlayer/daughters/name xlayer1 
/gate/zlayer/daughters/insert box
/gate/xlayer1/geometry/setXLength 3 mm    # Detector size
/gate/xlayer1/geometry/setYLength 3 mm    # Detector size
/gate/xlayer1/geometry/setZLength 3 mm    # Detector size
/gate/xlayer1/vis/setColor yellow
/gate/xlayer1/vis/forceSolid
/gate/xlayer1/setMaterial GAGG


/gate/zlayer/daughters/name xlayer2 
/gate/zlayer/daughters/insert box
/gate/xlayer2/geometry/setXLength 3 mm    # Detector size
/gate/xlayer2/geometry/setYLength 3 mm    # Detector size
/gate/xlayer2/geometry/setZLength 3 mm    # Detector size
/gate/xlayer2/vis/setColor yellow
/gate/xlayer2/vis/forceSolid
/gate/xlayer2/setMaterial GAGG

/gate/zlayer/daughters/name xlayer3 
/gate/zlayer/daughters/insert box
/gate/xlayer3/geometry/setXLength 3 mm    # Detector size
/gate/xlayer3/geometry/setYLength 3 mm    # Detector size
/gate/xlayer3/geometry/setZLength 3 mm    # Detector size
/gate/xlayer3/vis/setColor yellow
/gate/xlayer3/vis/forceSolid
/gate/xlayer3/setMaterial GAGG


/gate/zlayer/daughters/name xlayer4 
/gate/zlayer/daughters/insert box
/gate/xlayer4/geometry/setXLength 3 mm    # Detector size
/gate/xlayer4/geometry/setYLength 3 mm    # Detector size
/gate/xlayer4/geometry/setZLength 3 mm    # Detector size
/gate/xlayer4/vis/setColor yellow
/gate/xlayer4/vis/forceSolid
/gate/xlayer4/setMaterial GAGG

/gate/zlayer/daughters/name xlayer5 
/gate/zlayer/daughters/insert box
/gate/xlayer5/geometry/setXLength 3 mm    # Detector size
/gate/xlayer5/geometry/setYLength 3 mm    # Detector size
/gate/xlayer5/geometry/setZLength 3 mm    # Detector size
/gate/xlayer5/vis/setColor yellow
/gate/xlayer5/vis/forceSolid
/gate/xlayer5/setMaterial GAGG

/gate/zlayer/daughters/name xlayer6 
/gate/zlayer/daughters/insert box
/gate/xlayer6/geometry/setXLength 3 mm    # Detector size
/gate/xlayer6/geometry/setYLength 3 mm    # Detector size
/gate/xlayer6/geometry/setZLength 3 mm    # Detector size
/gate/xlayer6/vis/setColor yellow
/gate/xlayer6/vis/forceSolid
/gate/xlayer6/setMaterial GAGG

/gate/zlayer/daughters/name xlayer7 
/gate/zlayer/daughters/insert box
/gate/xlayer7/geometry/setXLength 3 mm    # Detector size
/gate/xlayer7/geometry/setYLength 3 mm    # Detector size
/gate/xlayer7/geometry/setZLength 3 mm    # Detector size
/gate/xlayer7/vis/setColor yellow
/gate/xlayer7/vis/forceSolid
/gate/xlayer7/setMaterial GAGG

/gate/zlayer/daughters/name xlayer8 
/gate/zlayer/daughters/insert box
/gate/xlayer8/geometry/setXLength 3 mm    # Detector size
/gate/xlayer8/geometry/setYLength 3 mm    # Detector size
/gate/xlayer8/geometry/setZLength 3 mm    # Detector size
/gate/xlayer8/vis/setColor yellow
/gate/xlayer8/vis/forceSolid
/gate/xlayer8/setMaterial GAGG



/gate/xlayer1/placement/setTranslation -12 0.18 0 mm
/gate/xlayer2/placement/setTranslation -9 0.81 0 mm
/gate/xlayer3/placement/setTranslation -6 -0.45 0 mm
/gate/xlayer4/placement/setTranslation -3 1.23 0 mm
/gate/xlayer5/placement/setTranslation 0 -0.87 0 mm
/gate/xlayer6/placement/setTranslation 3 1.65 0 mm
/gate/xlayer7/placement/setTranslation 6 -1.29 0 mm
/gate/xlayer8/placement/setTranslation 9 0.18 0 mm





/gate/panel/repeaters/insert ring
/gate/module/repeaters/insert linear
/gate/block/repeaters/insert linear
/gate/zlayer/repeaters/insert linear

/gate/xlayer1/repeaters/insert linear
/gate/xlayer2/repeaters/insert linear
/gate/xlayer3/repeaters/insert linear
/gate/xlayer4/repeaters/insert linear
/gate/xlayer5/repeaters/insert linear
/gate/xlayer6/repeaters/insert linear
/gate/xlayer7/repeaters/insert linear
/gate/xlayer8/repeaters/insert linear


/gate/panel/ring/setRepeatNumber 40
/gate/module/linear/setRepeatNumber 1
/gate/block/linear/setRepeatNumber 1
/gate/zlayer/linear/setRepeatNumber 1

/gate/xlayer1/linear/setRepeatNumber 16
/gate/xlayer1/linear/setRepeatVector 0.  6.72  0. mm

/gate/xlayer2/linear/setRepeatNumber 16  
/gate/xlayer2/linear/setRepeatVector 0  6.72   0. mm

/gate/xlayer3/linear/setRepeatNumber 16  
/gate/xlayer3/linear/setRepeatVector 0  6.72   0. mm

/gate/xlayer4/linear/setRepeatNumber 16  
/gate/xlayer4/linear/setRepeatVector 0  6.72  0. mm

/gate/xlayer5/linear/setRepeatNumber 16  
/gate/xlayer5/linear/setRepeatVector 0. 6.72 0. mm

/gate/xlayer6/linear/setRepeatNumber 16  
/gate/xlayer6/linear/setRepeatVector 0. 6.72 0. mm

/gate/xlayer7/linear/setRepeatNumber 16  
/gate/xlayer7/linear/setRepeatVector 0. 6.72 0. mm

/gate/xlayer8/linear/setRepeatNumber 32  
/gate/xlayer8/linear/setRepeatVector 0. 3.36 0. mm
